/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Users {
  avatar_url: string | null
  created_at: Timestamp
  email: string
  id: string
  name: string
  password: string
  role: Generated<number>
  updated_at: Timestamp
}

export interface DB {
  users: Users
}
